src/mycutc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from theme.views import IndexView

# Custom admin site settings
admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.index_title = settings.ADMIN_INDEX_TITLE

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('meetings/', include('meetings.urls', namespace='meetings')),
    path('trips/', include('trips.urls', namespace='trips')),
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/trips/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path

from .feeds import UpcomingTripsFeed
from .views import TripsListView, TripDetailView, TripCreateView, TripUpdateView, TripDeleteView, TripSignUpView, TripBailView

app_name = 'trips'

urlpatterns = [
    path('', TripsListView.as_view(), name='index'),
    path('feed/', UpcomingTripsFeed()),
    path('<int:pk>/', TripDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', login_required(TripUpdateView.as_view()), name='edit'),
    path('<int:pk>/delete/', login_required(TripDeleteView.as_view()), name='delete'),
    path('<int:pk>/signup/', login_required(TripSignUpView.as_view()), name='signup'),
    path('<int:pk>/bail/', login_required(TripBailView.as_view()), name='bail'),
    path('create/', login_required(TripCreateView.as_view()), name='create'),
]

src/trips/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.contrib.auth.models import User


class Trip(models.Model):
    # Basic
    name = models.CharField(max_length=250)
    description = models.TextField()

    # Date
    start = models.DateField()
    end = models.DateField()

    # Metadata
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trips:detail', args=[str(self.id)])

    def clean(self):
        if self.end < self.start:
            raise ValidationError({'end': 'The trip probably shouldn\'t end before it starts.'})


class TripParticipant(models.Model):
    # Always linked to user
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='participating_in')

    # Always linked to a trip
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='participants')

    # Number of seats in car, assume no car if 0
    seats = models.IntegerField()

    # Any notes to send to the trip leader, medical issues, other things
    notes = models.TextField()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

src/trips/forms.py
from django import forms

from .models import Trip

class DateInput(forms.DateInput):
    input_type = 'date'

class TripCreateForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['name', 'start', 'end', 'description']
        widgets = {
            'start': DateInput(),
            'end': DateInput()
        }

class TripSignupForm(forms.Form):
    do_you_have_a_car_and_can_drive = forms.BooleanField(required=False)
    number_of_seats_including_yourself = forms.ChoiceField(choices=[('1', '1'),
                                                                    ('2', '2'),
                                                                    ('3', '3'),
                                                                    ('4', '4'),
                                                                    ('5', '5'),
                                                                    ('6', '6'),
                                                                    ('7', '7'),
                                                                    ('8', '8'),
                                                                    ('9', '9'),
                                                                    ('10', '10'),
                                                                    ('11', '11'),
                                                                    ('12', '12)')], required=False)
    i_agree = forms.BooleanField(required=True)


class TripBailForm(forms.Form):
    i_agree = forms.BooleanField(required=False)

src/trips/views.py
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail

from .models import Trip, TripParticipant
from .forms import TripCreateForm, TripSignupForm, TripBailForm

import logging


class TripsListView(ListView):
    model = Trip
    context_object_name = 'trips'
    template_name = 'trips/index.html'
    queryset = Trip.objects.all().order_by('start')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context['upcoming_trips'] = self.queryset.filter(end__gte=now)
        context['past_trips'] = self.queryset.filter(end__lt=now)
        return context

class TripDetailView(DetailView):
    model = Trip
    template_name = 'trips/detail.html'

    def get_context_data(self, **kwargs):
        context = super(TripDetailView, self).get_context_data(**kwargs)
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        is_signed = False
        if self.request.user.is_authenticated:
            is_signed = trip.participants.filter(user=self.request.user)
        context['is_signed'] = is_signed
        return context

class TripCreateView(CreateView):
    model = Trip
    form_class = TripCreateForm
    template_name = 'trips/create.html'

    def form_valid(self, form):
        # Set creator to current user
        form.instance.creator = self.request.user
        return super().form_valid(form)

class TripUpdateView(UpdateView):
    model = Trip
    #fields = ('name', 'start', 'end', 'description',)
    form_class = TripCreateForm
    template_name = 'trips/edit.html'

    def form_valid(self, form):
        # Only creator can edit
        if form.instance.creator == self.request.user:
            return super().form_valid(form)
        else:
            raise PermissionDenied


class TripDeleteView(DeleteView):
    model = Trip
    template_name = 'trips/delete.html'
    success_url = reverse_lazy('trips:index')

    def delete(self, request, *args, **kwargs):
        # Only creator can delete
        self.object = self.get_object()

        if self.object.creator == self.request.user:
            return super().delete(self, request)
        else:
            raise PermissionDenied

class TripSignUpView(FormView):
    form_class = TripSignupForm
    template_name = "trips/signup.html"
    success_url = reverse_lazy('trips:index')

    def get_context_data(self, **kwargs):
        context = super(TripSignUpView, self).get_context_data(**kwargs)
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        context['trip'] = trip
        return context

    def form_valid(self, form):
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        seats = int(form.data['number_of_seats_including_yourself'])
        part = TripParticipant(user=self.request.user, trip=trip, seats=seats)
        part.save()

        send_mail('Trip signup',
                  '{} has signed up for your {} trip'.format(part.user.first_name, part.trip.name),
                  'no-reply@cutc.org.nz',
                  [trip.creator.email],
                  fail_silently=False)

        return super().form_valid(form)

class TripBailView(FormView):
    form_class = TripBailForm
    template_name = "trips/bail.html"
    success_url = reverse_lazy('trips:index')

    def get_context_data(self, **kwargs):
        context = super(TripBailView, self).get_context_data(**kwargs)
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        context['trip'] = trip
        return context

    def form_valid(self, form):
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        trip.participants.filter(user=self.request.user).delete()
        return super().form_valid(form)

src/trips/templates/trips/includes/trip_bail.html
{%  load bootstrap %}
<form action="." method="post">
    {% csrf_token %}
    <div>
        Are you sure you want to bail?<br>
        By bailing you understand that you give up your place on this trip and that someone else may take your place
    </div>
  <div class="form-group">
    <input type="submit" value="Bail" class="btn btn-danger" role="button" />
      <a href="{%  url 'trips:detail' trip.pk %}" class="btn btn-warning">Back</a>
  </div>
</form>

src/trips/templates/trips/includes/trip_confirm_delete.html
<form action="." method="post">
  {% csrf_token %}
  <p>Are you sure you want to delete <em>{{ trip.name }}</em>?</p>
  <p>This cannot be undone.</p>
  <div class="form-group">
    <input type="submit" value="Delete" class="btn btn-danger" role="button" />
  </div>
</form>

src/trips/templates/trips/includes/trip_detail.html
{% load markup_tags %}
<div class="trip-detail">
  <h2>Trip: {{ trip.name }}</h2>
  {%  if request.user.is_authenticated %}
      {%  if is_signed %}
          <a href="{%  url 'trips:bail' trip.pk %}" class="btn btn-danger">Bail</a>
      {%  else %}
          <a href="{%  url 'trips:signup' trip.pk %}" class="btn btn-primary">Sign up</a>
      {%  endif %}
  {% endif %}

    {%  if request.user == trip.creator %}
        {% include 'trips/includes/trip_participants.html' with trip=trip %}
    {%  endif %}

  {% ifequal trip.start trip.end %}
    <p>{{ trip.start }}</p>
  {% else %}
    <p>{{ trip.start }} to {{ trip.end }}</p>
  {% endifequal %}
  {% if trip.creator %}<p>Organiser: {{ trip.creator.get_full_name }}</p>{% endif %}
  <p class="enable-white-space">{{ trip.description|apply_markup:'markdown' }}</p>
  {% if request.user == trip.creator %}
    <a href="{% url 'trips:edit' trip.pk %}" class="btn btn-info">Edit</a>
    <a href="{% url 'trips:delete' trip.pk %}" class="btn btn-danger">Delete</a>
  {% endif %}
</div>

src/trips/templates/trips/includes/trip_form.html
{% load bootstrap %}
<form action="." method="post">
  {% csrf_token %}
  {{ form|bootstrap }}
  <div class="form-group">
    <input type="submit" value="Submit" class="btn btn-success" role="button" />
  </div>
</form>

src/trips/templates/trips/includes/trip_list.html
<div class="trip_list">
  {% if trips %}
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>When</th>
          <th>Description</th>
          <th><span class="sr-only">Actions</span></th>
        </tr>
      </thead>
      <tbody>
        {% for trip in trips %}
        <tr>
          <td><a href="{{ trip.get_absolute_url }}">{{ trip.name }}</a></td>
          <td>
            {% ifequal trip.start trip.end %}
              {{ trip.start }}
            {% else %}
              {{ trip.start }} to {{ trip.end }}
            {% endifequal %}
          </td>
          <td>{{ trip.description | truncatechars:100 }}</td>
          <td>
            <a href="{{ trip.get_absolute_url }}" class="card-link">View</a>
            {% if request.user == trip.creator %}
              <a href="{% url 'trips:edit' trip.pk %}" class="card-link">Edit</a>
              <a href="{% url 'trips:delete' trip.pk %}" class="card-link">Delete</a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
  {% else %}
  <p>No upcoming trips</p>
  {% endif %}
</div>

src/trips/templates/trips/includes/trip_participants.html
<div>
    <i>Participants:</i>
    {% for participant in trip.participants.all %}
        <p>{{ participant.user.first_name }} {{ participant.user.last_name }} - {{ participant.user.email }}</p>
    {%  endfor %}
</div>

src/trips/templates/trips/includes/trip_signup.html
{%  load bootstrap %}
<form action="." method="post">
    {% csrf_token %}
    <div>
            By signing up to this trip you agree to the following:
        <ul>
            <li>You are responsible for your own safety.</li>
            <li>You understand the risks.</li>
            <li>You understand the consequences.</li>
            <li>You understand the difficulty level of the trip, and ensures you have both the fitness and skills required</li>
            <li>Are aware of intended route/s and potential options for alternative routes</li>
            <li>You bring appropriate gear for trip</li>
            <li>Ensure the trip leader is aware of any allergies.</li>
            <li>Responsible for sticking with the group</li>
            <li>Responsible for your own food or food arrangements</li>
            <li>Pay for your share fuel or any other expenses involved in trip (such as hut fees)</li>
            <li>Are aware of club refund policy (as specified on webpage), and club gear locker policy if hiring gear?</li>
        </ul>
    </div>

    <h3>Please answer the following questions</h3>

    <div class="form-group">
        <label class="form-label">
            <input type="checkbox" name="do_you_have_a_car_and_can_drive" onclick="javascript:toggleDiv('have_car');">
            You have a car and are willing and licensed to drive
        </label>
    </div>

    <div id="have_car" style="display: none" class="form-group">
        <label class="form-label">
            <select name="number_of_seats_including_yourself" class="form-contorl">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
                <option value="6">6</option>
                <option value="7">7</option>
                <option value="8">8</option>
                <option value="9">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
            </select>
        <!--<input type="text" name="number_of_seats_including_yourself" class="form-control">-->
            Number of seat including yourself
        </label>
    </div>



    <div class="form-group form-check">
        <label class="form-check-label">
            <input type="checkbox" name="i_agree" class="form-check-input"> I Agree to the above conditions
            </label>
    </div>

    <div>
        Please click submit to complete your trip sign-up. If you change your mind or can no longer attend the trip, please contact the Trip Leader as soon as possible.
        You can expect to receive an email from the Trip Leader shortly to confirm attendance, equipment, and transport arrangements.
    </div>
  <div class="form-group">
    <input type="submit" value="Submit" class="btn btn-success" role="button" />
      <a href="{%  url 'trips:detail' trip.pk %}" class="btn btn-warning">Back</a>
  </div>
</form>