src/mycutc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from theme.views import IndexView

# Custom admin site settings
admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.index_title = settings.ADMIN_INDEX_TITLE

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('meetings/', include('meetings.urls', namespace='meetings')),
    path('trips/', include('trips.urls', namespace='trips')),
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/trips/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path

from .feeds import UpcomingTripsFeed
from .views import TripsListView, TripDetailView, TripCreateView, TripUpdateView, TripDeleteView, TripSignUpView, TripBailView

app_name = 'trips'

urlpatterns = [
    path('', TripsListView.as_view(), name='index'),
    path('feed/', UpcomingTripsFeed()),
    path('<int:pk>/', TripDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', login_required(TripUpdateView.as_view()), name='edit'),
    path('<int:pk>/delete/', login_required(TripDeleteView.as_view()), name='delete'),
    path('<int:pk>/signup/', login_required(TripSignUpView.as_view()), name='signup'),
    path('<int:pk>/bail/', login_required(TripBailView.as_view()), name='bail'),
    path('create/', login_required(TripCreateView.as_view()), name='create'),
]

src/meetings/models.py
from django.db import models
from django.urls import reverse

class Meeting(models.Model):
    # Basic
    name = models.CharField(max_length=250)
    location = models.CharField(max_length=250)
    description = models.TextField()

    # Date
    when = models.DateTimeField()

    # Metadata
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('meetings:detail', args=[str(self.id)])

src/theme/models.py
from django.db import models

# Create your models here.

src/trips/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.contrib.auth.models import User


class Trip(models.Model):
    # Basic
    name = models.CharField(max_length=250)
    description = models.TextField()

    # Date
    start = models.DateField()
    end = models.DateField()

    # Metadata
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trips:detail', args=[str(self.id)])

    def clean(self):
        if self.end < self.start:
            raise ValidationError({'end': 'The trip probably shouldn\'t end before it starts.'})


class TripParticipant(models.Model):
    # Always linked to user
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='participating_in')

    # Always linked to a trip
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='participants')

    # Number of seats in car, assume no car if 0
    seats = models.IntegerField()

    # Any notes to send to the trip leader, medical issues, other things
    notes = models.TextField()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

src/theme/views.py
from django.utils import timezone
from django.views.generic import TemplateView

from trips.models import Trip
from meetings.models import Meeting

class IndexView(TemplateView):
    template_name = "index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context['upcoming_trips'] = Trip.objects.filter(end__gte=now).order_by('start')
        context['upcoming_meetings'] = Meeting.objects.filter(when__gte=now).order_by('when')
        return context

src/theme/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "css/custom.css" %}">

      <script>
    function toggleDiv(divId) {
        $("#"+divId).toggle(500);
    }
    </script>

    <title>{% block title %}MyCUTC{% endblock title %}</title>
    {% block meta %}
    {% endblock meta %}
  </head>
  <body>
    {% block body %}

    {% block header %}
    <header>
      <div class="navbar navbar-dark navbar-expand-lg bg-dark">
        <div class="container">
          <a href="{% url 'index' %}" class="navbar-brand d-flex align-items-center">
            <img src="{% static 'img/mycutc_logo_white.svg' %}" alt="MyCUTC" class="d-inline-block align-middle my-2">
          </a><button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" data-reactid="9"><span class="navbar-toggler-icon" data-reactid="10"></span></button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item {% block index-active %}{% endblock %}">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
              </li>
              <li class="nav-item {% block trips-active %}{% endblock %}">
                <a class="nav-link" href="{% url 'trips:index' %}">Trips</a>
              </li>
              <li class="nav-item {% block meetings-active %}{% endblock %}">
                <a class="nav-link" href="{% url 'meetings:index' %}">Meetings</a>
              </li>
              <li class="nav-item {% block accounts-active %}{% endblock %}">
                {% if user.is_authenticated %}
                  <a class="nav-link" href="{% url 'auth_logout' %}">Logout</a>
                {% else %}
                  <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
                {% endif %}
              </li>
            </ul>
          </div>
        </div>
      </div>
    </header>
    {% endblock header %}

    {% block messages %}
      {% if messages %}
      <section class="container messages pt-3">
        {% for message in messages %}
        <div class="alert alert-info{% if message.tags %} {{ message.tags }}{% endif %}">
          {{ message }}
        </div>
        {% endfor %}
      </section>
      {% endif %}
    {% endblock messages %}

    <main role="main">
      {% block main %}
      {% endblock main %}
    </main>

    {% block footer %}
    <footer>
      <div class="container bg-light pt-3 pb-2 text-center small">

        <p>
          {% if user.is_authenticated %}
            <span>
              Logged in as <em>{{ user.email }}</em>
            </span>
          {% else %}
            <a class="nav-link" href="{% url 'auth_login' %}">Login</a>
          {% endif %}
        </p>
        <p>
          MyCUTC &middot; <a href="https://cutc.nz">Canterbury University Tramping Club</a>
          {% if user.is_superuser %}
            &middot; <a class="text-danger" href="{% url 'admin:index' %}">Committee Admin</a>
          {% endif %}
        </p>
      </div>
    </footer>
    {% endblock footer %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% endblock body %}
  </body>
</html>

src/theme/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home | MyCUTC{% endblock %}
{% block index-active %}active{% endblock %}

{% block main %}
  <div class="container banner" style="background-image: url({% static 'img/banner.jpg' %});">
    <div class="row">
      <div class="text col-lg-7 p-4">
        <h1 class="h2">
          Kia ora, welcome to MyCUTC
        </h1>
        <p class="lead">
          MyCUTC is the home of the Canterbury University Tramping Club's meetings and trips.
        </p>
        <p>
          This service is presently under construction, but you will soon be able to login, add and
          attend trips so long as you are a current member.
        </p>
      </div>
    </div>
  </div>
  <div class="container">
    <section class="py-4">
      <h2 class="h3">
        Upcoming Trips
        <small>
          <a href="{% url 'trips:index' %}">
            <span class="sr-only">All Trips</span>&raquo;
          </a>
        </small>
      </h2>
      {% include 'trips/includes/trip_list.html' with trips=upcoming_trips %}
    </section>
    <section class="py-4">
      <h2 class="h3">
        Upcoming Meetings
        <small>
          <a href="{% url 'meetings:index' %}">
            <span class="sr-only">All Meetings</span>&raquo;
          </a>
        </small>
      </h2>
      {% include 'meetings/includes/meeting_list.html' with meetings=upcoming_meetings %}
    </section>
  </div>
{% endblock main %}