src/mycutc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

from theme.views import IndexView

# Custom admin site settings
admin.site.site_header = settings.ADMIN_SITE_HEADER
admin.site.site_title = settings.ADMIN_SITE_TITLE
admin.site.index_title = settings.ADMIN_INDEX_TITLE

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('meetings/', include('meetings.urls', namespace='meetings')),
    path('trips/', include('trips.urls', namespace='trips')),
    path('accounts/', include('registration.backends.default.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

src/trips/urls.py
from django.contrib.auth.decorators import login_required, permission_required
from django.urls import path

from .feeds import UpcomingTripsFeed
from .views import TripsListView, TripDetailView, TripCreateView, TripUpdateView, TripDeleteView, TripSignUpView, TripBailView

app_name = 'trips'

urlpatterns = [
    path('', TripsListView.as_view(), name='index'),
    path('feed/', UpcomingTripsFeed()),
    path('<int:pk>/', TripDetailView.as_view(), name='detail'),
    path('<int:pk>/edit/', login_required(TripUpdateView.as_view()), name='edit'),
    path('<int:pk>/delete/', login_required(TripDeleteView.as_view()), name='delete'),
    path('<int:pk>/signup/', login_required(TripSignUpView.as_view()), name='signup'),
    path('<int:pk>/bail/', login_required(TripBailView.as_view()), name='bail'),
    path('create/', login_required(TripCreateView.as_view()), name='create'),
]

src/trips/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.contrib.auth.models import User


class Trip(models.Model):
    # Basic
    name = models.CharField(max_length=250)
    description = models.TextField()

    # Date
    start = models.DateField()
    end = models.DateField()

    # Metadata
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('trips:detail', args=[str(self.id)])

    def clean(self):
        if self.end < self.start:
            raise ValidationError({'end': 'The trip probably shouldn\'t end before it starts.'})


class TripParticipant(models.Model):
    # Always linked to user
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='participating_in')

    # Always linked to a trip
    trip = models.ForeignKey(Trip, on_delete=models.CASCADE, related_name='participants')

    # Number of seats in car, assume no car if 0
    seats = models.IntegerField()

    # Any notes to send to the trip leader, medical issues, other things
    notes = models.TextField()

    def __str__(self):
        return self.user.first_name + " " + self.user.last_name

src/trips/forms.py
from django import forms

from .models import Trip

class DateInput(forms.DateInput):
    input_type = 'date'

class TripCreateForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['name', 'start', 'end', 'description']
        widgets = {
            'start': DateInput(),
            'end': DateInput()
        }

class TripSignupForm(forms.Form):
    do_you_have_a_car_and_can_drive = forms.BooleanField(required=False)
    number_of_seats_including_yourself = forms.ChoiceField(choices=[('1', '1'),
                                                                    ('2', '2'),
                                                                    ('3', '3'),
                                                                    ('4', '4'),
                                                                    ('5', '5'),
                                                                    ('6', '6'),
                                                                    ('7', '7'),
                                                                    ('8', '8'),
                                                                    ('9', '9'),
                                                                    ('10', '10'),
                                                                    ('11', '11'),
                                                                    ('12', '12)')], required=False)
    i_agree = forms.BooleanField(required=True)


class TripBailForm(forms.Form):
    i_agree = forms.BooleanField(required=False)

src/trips/views.py
from django.utils import timezone
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView, FormView
from django.urls import reverse_lazy
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail

from .models import Trip, TripParticipant
from .forms import TripCreateForm, TripSignupForm, TripBailForm

import logging


class TripsListView(ListView):
    model = Trip
    context_object_name = 'trips'
    template_name = 'trips/index.html'
    queryset = Trip.objects.all().order_by('start')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        now = timezone.now()
        context['upcoming_trips'] = self.queryset.filter(end__gte=now)
        context['past_trips'] = self.queryset.filter(end__lt=now)
        return context

class TripDetailView(DetailView):
    model = Trip
    template_name = 'trips/detail.html'

    def get_context_data(self, **kwargs):
        context = super(TripDetailView, self).get_context_data(**kwargs)
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        is_signed = False
        if self.request.user.is_authenticated:
            is_signed = trip.participants.filter(user=self.request.user)
        context['is_signed'] = is_signed
        return context

class TripCreateView(CreateView):
    model = Trip
    form_class = TripCreateForm
    template_name = 'trips/create.html'

    def form_valid(self, form):
        # Set creator to current user
        form.instance.creator = self.request.user
        return super().form_valid(form)

class TripUpdateView(UpdateView):
    model = Trip
    #fields = ('name', 'start', 'end', 'description',)
    form_class = TripCreateForm
    template_name = 'trips/edit.html'

    def form_valid(self, form):
        # Only creator can edit
        if form.instance.creator == self.request.user:
            return super().form_valid(form)
        else:
            raise PermissionDenied


class TripDeleteView(DeleteView):
    model = Trip
    template_name = 'trips/delete.html'
    success_url = reverse_lazy('trips:index')

    def delete(self, request, *args, **kwargs):
        # Only creator can delete
        self.object = self.get_object()

        if self.object.creator == self.request.user:
            return super().delete(self, request)
        else:
            raise PermissionDenied

class TripSignUpView(FormView):
    form_class = TripSignupForm
    template_name = "trips/signup.html"
    success_url = reverse_lazy('trips:index')

    def get_context_data(self, **kwargs):
        context = super(TripSignUpView, self).get_context_data(**kwargs)
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        context['trip'] = trip
        return context

    def form_valid(self, form):
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        seats = int(form.data['number_of_seats_including_yourself'])
        part = TripParticipant(user=self.request.user, trip=trip, seats=seats)
        part.save()

        send_mail('Trip signup',
                  '{} has signed up for your {} trip'.format(part.user.first_name, part.trip.name),
                  'no-reply@cutc.org.nz',
                  [trip.creator.email],
                  fail_silently=False)

        return super().form_valid(form)

class TripBailView(FormView):
    form_class = TripBailForm
    template_name = "trips/bail.html"
    success_url = reverse_lazy('trips:index')

    def get_context_data(self, **kwargs):
        context = super(TripBailView, self).get_context_data(**kwargs)
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        context['trip'] = trip
        return context

    def form_valid(self, form):
        trip = Trip.objects.get(pk=self.kwargs['pk'])
        trip.participants.filter(user=self.request.user).delete()
        return super().form_valid(form)

src/trips/templates/trips/bail.html
{%  extends 'trips/base.html' %}

{% block title %}{{ trip.name }} | MyCUTC{% endblock %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'trips:index' %}">Trips</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ trip.name }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
    {% include 'trips/includes/trip_bail.html' with trip=trip %}
{% endblock content %}

src/trips/templates/trips/base.html
{% extends 'base.html' %}

{% block title %}Trips | MyCUTC{% endblock %}
{% block trips-active %}active{% endblock %}

{% block main %}
  <div class="container py-4">
    {% block breadcrumbs %}
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page"><a href="{% url 'trips:index' %}">Trips</a></li>
      </ol>
    </nav>
    {% endblock %}

    <h1>{% block page-header %}Trips{% endblock %}</h1>

    {% block content %}{% endblock %}
  </div>
{% endblock main %}

src/trips/templates/trips/create.html
{% extends 'trips/base.html' %}

{% block title %}Create Trip | MyCUTC{% endblock %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'trips:index' %}">Trips</a></li>
    <li class="breadcrumb-item active" aria-current="page">Create Trip</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
    {% include 'trips/includes/trip_form.html' with form=form %}
{% endblock content %}

src/trips/templates/trips/delete.html
{% extends 'trips/base.html' %}

{% block title %}Deleting {{ trip.name }} | MyCUTC{% endblock %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'trips:index' %}">Trips</a></li>
    <li class="breadcrumb-item active" aria-current="page"><em>Deleting</em> {{ trip.name }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
  {% include 'trips/includes/trip_confirm_delete.html' with trip=trip %}
{% endblock content %}

src/trips/templates/trips/detail.html
{% extends 'trips/base.html' %}

{% block title %}{{ trip.name }} | MyCUTC{% endblock %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'trips:index' %}">Trips</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ trip.name }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
    {% include 'trips/includes/trip_detail.html' with trip=trip %}
{% endblock content %}

src/trips/templates/trips/edit.html
{% extends 'trips/base.html' %}

{% block title %}Editing {{ trip.name }} | MyCUTC{% endblock %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'trips:index' %}">Trips</a></li>
    <li class="breadcrumb-item active" aria-current="page"><em>Editing</em> {{ trip.name }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
  {% include 'trips/includes/trip_form.html' with form=form %}
{% endblock content %}

src/trips/templates/trips/index.html
{% extends 'trips/base.html' %}

{% block content %}
  <p><a href="{% url 'trips:create' %}" class="btn btn-success" role="button">Create</a></p>
  {% include 'trips/includes/trip_list.html' with trips=upcoming_trips %}
{% endblock content %}

src/trips/templates/trips/signup.html
{%  extends 'trips/base.html' %}

{% block title %}{{ trip.name }} | MyCUTC{% endblock %}

{% block breadcrumbs %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{% url 'trips:index' %}">Trips</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ trip.name }}</li>
  </ol>
</nav>
{% endblock %}

{% block content %}
    {% include 'trips/includes/trip_signup.html' with trip=trip %}
{% endblock content %}